:toc: macro
:toc-title: Оглавление
:icons: font

include::Titul_list_report3.adoc[]

toc::[]

---
[.text-left]
== Цель лекции
Изучение указателей и ссылок, а также операций связанных с ними.

== Теоретические основы
=== Указатели
Данные могут находится в ОЗУ или ПЗУ. Каждой переменной содержащей данные соответствует некоторый адрес памяти. К переменной можно обратиться непосредственно обращаясь к самой переменной, тогда мы можем напрямую писать или читать значение с адреса переменной, либо можно обратиться косвенно, через указатель или ссылку.

*Указатель* - это переменная, которая хранит адрес другой переменной.

=== Взятие адреса и разыменование указателя.

 Для того чтобы узнать адрес переменной, используется оператор взятия адреса _&_ +

.Пример:
[source, cpp, linenums]

----
char* Ptr = &a;

----

<<<

WARNING: Тип указателя должен совпадать с типом переменной!

 *Разыменовывание* - обратная операция операции взятия адреса, которая выводит значение, хранимое по адресу указанному в указателе.

=== Операции над указателями
Указатели можно складывать с целым числом, вычитать, сравнивать. Но указатели должны быть одного типа. 

==== Сложение/Вычитание
При прибавлении к указателю числа адрес переменной, который хранит данный указатель, увеличивается на размерность типа указателя.

*Инкрементирование* - сложение указателей.
*Дикрементирование* - вычитание указателей.

==== Сравнение указателей
Сравнение указателей является фактическим сравнением адресов, переменных. 

[IMPORTANT]
Нельзя сравнивать указатели разных типов!

WARNING: Компилятор не умеет работать с нулевым указателем

=== Константный указатель и указатель на константу
*Константный указатель* - данный указатель неьзя менять, инкрементировать, дикрементировать, возможно только сравнивать. +
*Указатель на константу* - в некоторых случаях изменить указатель можно, а значение переменной, хранимой по адресу указанному в указателе - нет.

=== Ссылка
*Ссылка* - это псевдоним переменной.

.Пример:
[source, cpp, linenums]

----
double* a; //указатель
double& a; //ссылка
double a = &b; //взятие адреса (для указателя)
----

<<<

*_Особенности:_* +
* У ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведен адрес переменной, на которую она ссылается +
* Ссылка ведет себя почти также как константный указатель. То есть над ней нельзя проделывать операции, такие как: сложение, вычитание и пр. +
* Ссылки нельзя сравнивать +
* Ссылка не может быть не проинициализирована.

Ссылка по свойствам похожа на константный указатель.

== Выводы
[.text-left]
Прослушав данную лекцию были изучены указатели и ссылки, как операторы для работы с адресами переменных.

Получена _новая_ информация об операциях, которые можо проводить над указателями.Изучены новые понятия, такие как "Константный указател" и "Ссылка". Получены сведения о взятии адреса и разименовывания указателя.

//[.text-center]
//== Ответы на контрольные вопросы
//[.text-left]
//*Кортеж* -  это упрощенная структура данных, которая имеет определенное число и последовательность значений. При создании экземпляра кортежа определяется число и тип данных каждого значения (или элемента).
