:toc: macro

:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::/*Titul_list_Laba1.adoc[]*/

toc::[]

---
[.text-left]
== Цель лабораторной работы

== Задание
=== 1. Регистры 

Регистры - это ячейки памяти процессора, предназначенные для хранения адресов и результатов вычислений.

* Существуют регистры общего назначения и специальные регистры. Регистры общего назначения расположены внутри ядра микроконтроллера(сверхбыстрая память).

* Регистры общего назначения - это сверхбыстрая память внутри процессора, предназначенная для хранения адресов и промежуточных результатов вычислений (регистр общего назначения/регистр данных) или данных, необходимых для работы самого процессора.

* Регистры специального назначения расположены в ОЗУ микроконтроллера и используются для управления процессором и периферийными устройствами.

* Каждый регистр в архитектуре ARM представляет собой ресурс памяти и имеет длину в 32 бита, где каждый бит можно представить в виде выключателя с помощью которого осуществляется управление тем или иным параметром микроконтроллера

*Регистры общего назначения*
Процессор располагает 16-ю 32-разрядными регистрами общего назначения (РОН, GPR), из которых три имеют специальные функции:

1. Оперативные регистры
2. Вспомогательные регистры
3. Специальные регистры

----
1. Оперативные регистры
Регистры R0-R3, R12 являются оперативными(sratch) регистрами. Любая функция может использовать эти регистры по своему усмотрению и уничтожать содержимое этих регистров.

Для использования регистра несколькими функциями, необходимо чтобы каждая "новая" функция сохраняла их на стеке и после вызова восстанавливала.

2. Вспомогательные регистры
Регистры от R4-R11 являются вспомогательными. 
Любая функция должна сохранить их на входе, а при выходе восстановить их значение. (как при использовании оперативных регистров нескольими функциями)

3. Специальные регистры
R13/SP - регистр указателя на стек

[IMPORTANT]
R13/SP должен всегда указывать на последний элемент стека или ниже него.

R15/PC - программный счетчик.
R14/LR - адрес возврата функции. //Содержит его
----
<<<<

Адрес регистра обозначается 32-битным шестнадцатеричным числом.
----
Длина - количество ячеек в одном регистре.

Поле - набор ячеек регистра, отвечающих за работу одной из функции микроконтроллера

Значение поля - есть пространство всех возможных величин, которые может принимать поле
----
<<<<
Значение поля зависит от длины поля. 

*Доступ к регистру специального назначения*
Так как регистр специального назначения - это просто адресуемая ячейка памяти, то в коде возможно обратиться к данным по этому адресу, разыменовывая указатель, указывающий на этот адрес.

*Работа с регистрами периферии через обертку на С++*
Для того, чтобы настроить определенное периферийное устройство процессора, необходимо изменить значение поля в соответствующем регистре.

Для более удобной работы с регистрами можно использовать С++ обертку. Эта обертка позволяет обращаться к регистрам в форме очень похоже с тем, как эти регистры описаны в документации.

=== 2. Написать код программы для работы со светодиодами через регистры микроконтроллера.

Был написан код, в котором проводится взаимодействие с регистрами.

На видео показан результат работы программы (кода).

video::VID_1.mp4[opts="muted"]

[.text-left]

== Выводы
[.text-left]
//Выводы по лабораторной работе

[.text-center]
== Ответы на контрольные вопросы
[.text-left]
// закоментировать или убрать, если таковых нет