
:toc: macro

include::Titul_list_Report1.adoc[]

toc::[]

[.text-center]
== Запуск программного обеспечения на микроконтроллере
[.text-left]
При запуске программы на контроллер подается питание. После чего контроллер переходит по адресу _0x800’0000_, срабатывает счетчик команд. +
*Счетчик команд* – это специализированный внутренний регистр микроконтроллера, в котором хранится адрес текущей выполняемой команды. +
Контроллер выполняет команду (счетчик команд увеличивается на единицу). Выполняя команды, т.е. переходя, в соответствующем порядке, по адресам и выполняя прописанные команды. +
Происходит переход в _таблицу векторов прерывания_, которая представляет из себя массив адресов. +
_«Точка входа программы»_ расположена в качестве адреса или команды перехода в таблице векторов прерывания. +
По первому адресу происходит инициализация стека, который нужен для оперативного сохранения временных значении (область памяти). Предварительно необходимо задать в указателе стека адрес последней ячейки (Регистр SP). +
*Стек* – абстрактный тип данных, представляющий собой список элементов, организованных по принципу LIFO. Чаще всего принцип работы стека сравнивают со стопкой тарелок: чтобы взять вторую сверху, нужно снять верхнюю. +
Далее происходит инициализация стека. +
По следующему адресу записан адрес программы _«IAR_Programm_Start»_, на которую нужно перейти. +
Предварительно происходит инициализация глобальных переменных (Сначала – нулевые, потом – ненулевые). Также происходит инициализация ядра и других основных функций. +
Далее происходит переход к функции _«main»_. +
В компиляторе происходит трансляция кода в объектный файл, который в свою очередь преобразуется Linker в двоичный код, параллельно создается map-файл (в нем прописаны адреса переменных и т.д.).

[.text-center]
== Выводы
[.text-left]
Выполняя данную работу был изучен процесс зауска программного обеспеченя на микроконтроллере, включая: инициализацию переменных, переход в таблицу векторов прерывания, запуск функции "main" и многое другое. +
Результатом работы является большее понимание работы микроконтроллера.

[.text-center]
== Ответы на контрольные вопросы
[.text-left]
1.  Дайте определение понятию «Интегрированной среде разработки». +
Ответ: +
*Интегрированная среда разработки* - программа, в которой разработчики пишут, проверяют, тестируют и запускают код, а также ведут большие проекты. Она включает в себя сразу несколько инструментов: редактор для написания кода, сервисы для его проверки и запуска, расширения для решения дополнительных задач разработки.

2.  Что такое компилятор и чем он отличается от транслятора? +
Ответ: +
*Компилятор* - транслятор, который осуществляет перевод исходной программы в эквивалентную ей объектную программу на языке машинных команд или языке ассемблера. +
*Транслятор* - программа, которая переводит входную программу на исходном (входном) языке в эквивалентную ей выходную программу на результирующем (выходном) языке. +
Компилятор отличается от транслятора тем, что его результирующая программа всегда должна быть написана на языке машинных кодов или на языке ассемблера. Результирующая программа транслятора, в общем случае, может быть написана на любом языке. Соответственно, всякий компилятор является транслятором, но не наоборот.

3.  Что такое компоновщик и какие функции он выполняет? +
Ответ: +
*Компоновщик* (от англ. link editor, linker) — инструментальная программа, которая производит компоновку («линковку»): принимает на вход один или несколько объектных модулей и собирает из них исполняемый или библиотечный файл-модуль. +
Для большинства компиляторов один объектный файл является результатом компиляции одного файла с исходным кодом. Если программа собирается из нескольких объектных файлов, компоновщик собирает эти файлы в единый исполняемый файл, вычисляя и подставляя адреса вместо символов, в течение времени компоновки (статическая компоновка) или во время исполнения (динамическая компоновка). +
Компоновщик может извлекать объектные файлы из специальных коллекций, называемых библиотеками. Если не все символы, на которые ссылаются пользовательские объектные файлы, определены, то компоновщик ищет их определения в библиотеках, которые пользователь подал ему на вход. Обычно одна или несколько системных библиотек используются компоновщиком по умолчанию. Когда объектный файл, в котором содержится определение какого-либо искомого символа, найден, компоновщик может включить его (файл) в исполняемый файл (в случае статической компоновки) или отложить это до момента запуска программы (в случае динамической компоновки). +
Работа компоновщика заключается в том, чтобы в каждом модуле определить и связать ссылки на неопределённые имена. Для каждого импортируемого имени находится его определение в других модулях, упоминание имени заменяется на его адрес.+
Компоновщик обычно не выполняет проверку типов и количества параметров процедур и функций. Если надо объединить объектные модули программ, написанные на языках со строгой типизацией, то необходимые проверки должны быть выполнены дополнительной утилитой перед запуском редактора связей.
4.  Почему важен процесс проектирования ПО какие задачи входят в этот процесс? +
Ответ: +
При разработке программного обеспечения начинать следует с проектирования — т.е. с полного планирования того, что непосредственно придётся разрабатывать, в какие сроки, с какими исходными данными и ожидаемым результатом. +
Определив требования к программному обеспечению, разработчик получает согласованный четкий план действий, график оплат и сроков, сокращает время разработки и повышает её качество, а также позволяет предусмотреть любые другие нюансы разработки, например, юридические (в частности по передаче авторских прав на программное обеспечение). +
Проектируя ПО заранее, разработчик получает возможность:
•   оценить стоимость и время разработки программного продукта,
•   исключить потери времени и денег на ненужные действия, вынужденные доработки, длительное согласование,
•   избежать разногласий и неудовлетворённости клиента и исполнителя. +
[.text-left]
При подготовке к проектированию решаются организационные вопросы:
•   что клиент может предоставить (ТЗ, макеты, дизайн), насколько достаточны исходники и какие этапы закрывают — таким образом определяется состав работ,
•   бюджет и сроки: на основе имеющихся материалов утверждается примерная стоимость, срок всего проекта, а также срок и точная стоимость ближайшего этапа.
5.  Дорисуйте процесс разработки ПО, описанный на изображении «Процесс разработки с точки зрения IAR Workbench» с учетом итеративности связей в этом процессе. +
Ответ: (-)
6.  Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки? +
Ответ: +
*Отладка* – это процесс поиска и исправления ошибок или неполадок в исходном коде какого-либо программного обеспечения. +
Отладка необходимо для устранения неисправностей работы готовой программы. +
Преднамеренное прерывание выполнения программы, при котором выполняется вызов отладчика. +
После перехода к отладчику программист может исследовать состояние программы (логи, состояние памяти, регистров процессора, стека и т. п.), с тем чтобы определить, правильно ли ведёт себя программа. В отличие от полной остановки, с помощью останова, после работы в отладчике программа может быть завершена либо продолжена с того же места, где произошёл останов.
7.  Какие еще важные IAR workbench можно добавить в таблицу «Характеристики IAR»? +
Ответ:   (-)
