:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::Titul_list_Laba8.adoc[]

toc::[]

---
[.text-left]
== Цель и задание лабораторной работы
Написать программу, которая будет переключать все светодиоды с периодом 0,5 секунды. По нажатию кнопки увеличивать период моргания на 0,1 секунды. При достижении периода 1 секунда сбрасывать до начального периода (0,5 секунды). Для задания периода использовать таймер TIM5 (для данного варианта), а прерывания для кнопки сделать через TIM2.

== Прерывания
Прерывание - это сигнал, сообщающий микропроцессору о наступлении какого-либо события от переферии. При этом выполнение текущей последовательности команд останавливается, и управление передаётся обработчику прерывания, который реагирует на событие и обслуживает его, после чего возвращает управление в прерванный код.

В зависимости от источника прерывания бывают:
* асинхронные;
* синхронные;
* программные.

Различают маскируемые и немаскируемые прерывания.

Управление и обработка прерываниями производится контроллером приоритетных векторных прерываний (NVIC), который является частью ядра Cortex-M.
== Ход работы


== Выводы
[.text-left]
//Выводы по лабораторной работе

[.text-center]
== Ответы на контрольные вопросы
[.text-left]
// закоментировать или убрать, если таковых нет
