:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::Titul_list_Laba8.adoc[]

toc::[]

---
[.text-left]
== Цель и задание лабораторной работы
Написать программу, которая будет переключать все светодиоды с периодом 0,5 секунды. По нажатию кнопки увеличивать период моргания на 0,1 секунды. При достижении периода 1 секунда сбрасывать до начального периода (0,5 секунды). Для задания периода использовать таймер TIM5 (для данного варианта), а прерывания для кнопки сделать через TIM2.

== Прерывания
Прерывание - это сигнал, сообщающий микропроцессору о наступлении какого-либо события от переферии. При этом выполнение текущей последовательности команд останавливается, и управление передаётся обработчику прерывания, который реагирует на событие и обслуживает его, после чего возвращает управление в прерванный код.

В зависимости от источника прерывания бывают:
* асинхронные;
* синхронные;
* программные.

Различают маскируемые и немаскируемые прерывания.

Управление и обработка прерываниями производится контроллером приоритетных векторных прерываний (NVIC), который является частью ядра Cortex-M.

== Ход работы

В startupF411RE.cpp были добавлены строчки:
[source, cpp, linenums]
----
#include "timerconfig.h"
tTimer2::handler,             //TIM2  	
tTimer5::handler,	        //TIM5 global interrupt
----

Листинг pin.h

[source, cpp, linenums]
----

----

Листинг imode.h

[source, cpp, linenums]
----

----

Листинг alldiod.h

[source, cpp, linenums]
----

----

Листинг garland.h

[source, cpp, linenums]
----

----

Листинг ibutton.h

[source, cpp, linenums]
----

----

Листинг button.h

[source, cpp, linenums]
----

----


Листинг timerconfig.h

[source, cpp, linenums]
----

----


Листинг timer2.h

[source, cpp, linenums]
----

----

Листинг timer5.h

[source, cpp, linenums]
----

----

Листинг main.cpp

[source, cpp, linenums]
----

----

//.Работа кода
//video::__.mp4[]

== Выводы
[.text-left]
В ходе данной работы было проведено ознакомление с прерываниями. Была написана программа, которая реализует переключение светодиодов при помощи прерываний и проверяет нажата ли кнопка через прерывание, по нажатию менялся период "моргания" на 0,1 секунды.