:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::Titul_list_Laba5.adoc[]

toc::[]

---
[.text-left]
== Цель лабораторной работы

== Теоретическая часть
[.text-left]
SOLID (сокр. от англ. single responsibility, open–closed, Liskov substitution, interface segregation и dependency inversion) в программировании — мнемонический акроним, введённый Майклом Фэзерсом (Michael Feathers) для первых пяти принципов, названных Робертом Мартином в начале 2000-х, которые означали 5 основных принципов объектно-ориентированных проектирования и программирования.

=== Принципы
Избавиться от «признаков плохого проекта» помогают следующие 5 принципов SOLID:

[#Принципы SOLID]
.Принципы SOLID
[options="header"]
[cols="1,2,7"]
|=====================
|Инициал | Представляет |Название, понятие
|*S*|SRP|Принцип единственной ответственности (_single responsibility principle_)
Для каждого класса должно быть определено единственное назначение. Все ресурсы, необходимые для его осуществления, должны быть инкапсулированы в этот класс и подчинены только этой задаче.
|*O*|OCP|Принцип открытости/закрытости (_open-closed principle_) «программные сущности … должны быть открыты для расширения, но закрыты для модификации».
|*L*|LSP|Принцип подстановки Лисков (_Liskov substitution principle_) «функции, которые используют базовый тип, должны иметь возможность использовать подтипы базового типа не зная об этом». См. также контрактное программирование.
|*I*|ISP|Принцип разделения интерфейса (_interface segregation principle_) «много интерфейсов, специально предназначенных для клиентов, лучше, чем один интерфейс общего назначения».
|*D*|DIP|Принцип инверсии зависимостей (_dependency inversion principle_) «Зависимость на Абстракциях. Нет зависимости на что-то конкретное».
|=====================

=== Для чего нужны принципы SOLID
При создании программных систем использование принципов SOLID способствует созданию такой системы, которую будет легко поддерживать и расширять в течение долгого времени. +
Принципы SOLID — это руководства, которые также могут применяться во время работы над существующим программным обеспечением для его улучшения.

== Практическая часть
=== Задание
Написать программу, реализующую алгоритм "шахматы": включить нечетные светодиоды, задержка, выключить нечетные и включить четные светодиоды, задержка и т.д. Выполнить основную часть программы с помощью отдельного класса.

Листинг pin.h
[source, cpp, linenums]
----
#ifndef PIN
#define PIN

#include "gpiocregisters.hpp" // for GPIOC
#include "gpioaregisters.hpp" // for GPIOA
#include "IPin.h" // for IPin

template<typename Port, int pinNumber>
class Pin : public IPin
{
public:
  void Toggle() const override
  {
    Port::ODR::Toggle(1 << pinNumber) ;
  }
} ;

#endif
----

Листинг ipin.h
[source, cpp, linenums]
----
#ifndef IPIN
#define IPIN

class IPin
{
public:
  virtual void Toggle() const = 0;
};

#endif
----

Листинг imode.h
[source, cpp, linenums]
----
#ifndef IMODE
#define IMODE

class IMode
{
public:
  virtual void Update() = 0;
};

#endif
----

Листинг chess.h
[source, cpp, linenums]
----
#ifndef CHESS
#define CHESS

#include "imode.h" // for IMode
#include <array>

template<auto&...pins>
class Chess : public IMode
{
private:
  bool flag = true;
public:
  void Update() override
  {
    if(flag) // нечетные светодиоды
    {
      for(std::size_t i = 0; i < leds.size(); i+=2)
      {
        leds[i]->Toggle();
      }
    } else // четные светодиоды
    {
      for(auto it: leds)
      {
        it->Toggle();
      }
    }
    flag = false;
  }
private:
  std::array<IPin*, sizeof ...(pins)> leds = {&pins...};
};

#endif
----

Листинг main.cpp
[source, cpp, linenums]
----
#include "rccregisters.hpp" // for RCC
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPIOC
#include "Pin.h"
#include "IPin.h"
#include <iostream>
#include <array>
//#include "treeng.h" // for Treeng
#include "chess.h" // for ChessMode

std::uint32_t SystemCoreClock = 16'000'000U;

void delay(int cycles)
    {
      for(int i = 0; i < cycles; ++i)
      {
        asm volatile("");
      }
    }

Pin<GPIOA,5> pin1 ;
Pin<GPIOC,9> pin2 ;
Pin<GPIOC,8> pin3 ;
Pin<GPIOC,5> pin4 ;
Chess<pin1, pin2, pin3, pin4> chess;
int main()
{

    //Подать тактирование на порт A
  RCC::AHB1ENR::GPIOAEN::Enable::Set() ;
  //Подать тактирование на порт С
  RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
  //Установка порта А (GPIOA) 5 бит (MODER5) на выход
  GPIOA::MODER::MODER5::Output::Set() ;
  //Порт С.5
  GPIOC::MODER::MODER5::Output::Set() ;
  //Порт С.8
  GPIOC::MODER::MODER8::Output::Set() ;
  //Порт с.9
  GPIOC::MODER::MODER9::Output::Set() ;

  for(;;)
  {
    // Гирлянда: зажечь 1 светодиод, задержка, 2, задержка и т.д. И потом также гасить
    //treeng.Update();
    //шахматы
    chess.Update();
    delay(1000000);
  }
  return 1;
}
----

.Видео - "Шахматы"
video::VID5_Шахматы.mp4[opts="muted"]


== Выводы
[.text-left]
В ходе данной работы были описаны принципы программирования SOLID, а также с помощью данных принципов, написана программа, переключающая светодиоды по алгоритму "шахматы".

//[.text-center]
//== Ответы на контрольные вопросы
//[.text-left]
// закоментировать или убрать, если таковых нет

