:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::Titul_list_Laba5.adoc[]

toc::[]

---
[.text-left]
== Цель лабораторной работы

== Теоретическая часть
[.text-left]
SOLID (сокр. от англ. single responsibility, open–closed, Liskov substitution, interface segregation и dependency inversion) в программировании — мнемонический акроним, введённый Майклом Фэзерсом (Michael Feathers) для первых пяти принципов, названных Робертом Мартином в начале 2000-х, которые означали 5 основных принципов объектно-ориентированных проектирования и программирования.

=== Принципы
Избавиться от «признаков плохого проекта» помогают следующие 5 принципов SOLID:

[#Принципы SOLID]
.Принципы SOLID
[options="header"]
[cols="1,2,7"]
|=====================
|Инициал | Представляет |Название, понятие
|*S*|SRP|Принцип единственной ответственности (_single responsibility principle_)
Для каждого класса должно быть определено единственное назначение. Все ресурсы, необходимые для его осуществления, должны быть инкапсулированы в этот класс и подчинены только этой задаче.
|*O*|OCP|Принцип открытости/закрытости (_open-closed principle_) «программные сущности … должны быть открыты для расширения, но закрыты для модификации».
|*L*|LSP|Принцип подстановки Лисков (_Liskov substitution principle_) «функции, которые используют базовый тип, должны иметь возможность использовать подтипы базового типа не зная об этом». См. также контрактное программирование.
|*I*|ISP|Принцип разделения интерфейса (_interface segregation principle_) «много интерфейсов, специально предназначенных для клиентов, лучше, чем один интерфейс общего назначения».
|*D*|DIP|Принцип инверсии зависимостей (_dependency inversion principle_) «Зависимость на Абстракциях. Нет зависимости на что-то конкретное».
|=====================

=== Для чего нужны принципы SOLID
При создании программных систем использование принципов SOLID способствует созданию такой системы, которую будет легко поддерживать и расширять в течение долгого времени. +
Принципы SOLID — это руководства, которые также могут применяться во время работы над существующим программным обеспечением для его улучшения.

== Практическая часть
=== Задание
Написать программу, реализующую алгоритм "шахматы": включить нечетные светодиоды, задержка, выключить нечетные и включить четные светодиоды, задержка и т.д. Выполнить основную часть программы с помощью отдельного класса.


== Выводы
[.text-left]
//Выводы по лабораторной работе

//[.text-center]
//== Ответы на контрольные вопросы
//[.text-left]
// закоментировать или убрать, если таковых нет

