:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::Titul_list_Laba7.adoc[]

toc::[]

---
[.text-left]
== Цель лабораторной работы
Изучить назначения таймеров в микроконтроллерах. Научится использовать таймеры при написании программы.

== Задание

[.text-left]
Написать программу, которая будет переключать все светодиоды с периодом 0,5 секунды. По нажатию кнопки увеличивать период моргания на 0,1 секунды. При достижении периода 1 секунда сбрасывать до 0,5 секунды. Для задания периода использовать таймер TIM5 (для данного варианта).

== Теоритические основы
=== Таймеры
Одна из основных задач таймеров в микроконтроллерах это отсчитывать точные интервалы времени. +
Также таймеры могут использоваться для измерения частоты, периодов, генерации ШИМ-сигналов и переменных сигналов различной формы.

Микроконтроллер STM32F411 имеет:

* системный таймер (SYSTEM TIMER) - простой таймер, встроенный в ядро, имеет 24 бита;
* TIM1 - расширенный 16-битный таймер;
* TIM2-TIM5 - таймеры общего назначения, причем TIM2 и TIM5 32-битные, а остальные 16-битные;
* TIM9-TIM11 - 16-битные таймеры.

=== Системный таймер
Самый просто таймер, встроенный в ядро ARMv7, на котором построено ядро CortexM4, его поддерживают все микроконтроллеры на этом ядре.

* 24 - битный таймер считающий вниз от заданного значения до нуля;
* используется только 3 регистра для настройки:
1. SysTick Control and Status Register (SYST_CSR) (регистр для управления системным таймером),
2. Регистр перезагружаемого значения LOAD (В этом регистре хранится значение, которое будет записано в системный таймер как только его счетчик достигнет 0),
3. Регистр текущего значения VAL (В этом регистре хранится текущее значение счетчика).

=== Таймеры TIM2 и TIM5
* Таймеры 32 битные;
* Таймеры тактируются от шины APB1; 
* умеют работатьс инкрементальными энкодерами и датчиками Холла;
* несколько таймеров можно синхронизировать между собой.
* Таймеры могут использоваться для:
** Захвата сигнала (Защелкивать значение, когда на выводе порта например 0 сменился на 1)
** Сравнения (Считать до значения в регистре сравнения и установить/сбросить/переключить вывод порта)
** Генерации ШИМ (Генерировать прямоугольный сигнал с различной скважностью на вывод порта)
** Генерации одиночного импульса;
* Таймеры могут генеририровать следующие события:
** Переполнение
** Захват сигнала
** Сравнение
** Событие-триггер

[.notes]
--
Поэтому для каждый отчсет таймера по умолчанию происходит на частоте шины, т.е. если шина *APB1* работает на частоте 1 Мгц,
то один отсчет таймера произойдет через 1 мкс. Таким образом можно организовать измерение времени с разрешением в 1 мкс.
Чтобы таймер заработал, его нужно подключить к системе тактирования, т.е. к шине *APB1*.
--

* Подключение к системе тактирование выполняется через регистр *APB1ENR* модуля *RCC*.

* Входную частоту таймера можно поделить, записав делитель частоты в решистр *PSC*.

* Включение таймера производиться с помощью бита *CEN* в регистре *CR1* модуля таймера (TIM2 или TIM5)


=== Таймеры TIM2 и TIM5 переполнение

[.notes]
--
Как только таймер начал считать, его счетчик будет увеличиваться с каждым тактом подающейся на таймер частоты. Т.е. если
входная частота таймера 1 МГц, то через секунду таймер достчитает до 1 000 000.
--

* Значение счетчика таймера можно прочитать из регистра *CNT*.
- Поскольку таймерs *TIM2* и *TIM5* 32 битных, то переполнение наступит когда в регистре *CNT* будет значение *0xFFFFFFFF*,
нетрудно посчитать, что при частоте работе таймера 1 МГц он переполнится через примерно 71.5 минуты.
- При переполнении таймера, он сгенерирует событие (запрос на прерывание).

* Проверить случилось ли переполнение можно, считав бит *UIF* в регистре *CR*.

Настройка таймеров происходит с помощью записи в их регистры нужных бит.

В данной работе будет использоваться таймер TIM5, поэтому рассмотрим его подробнее. Таймер TIM5 тактируется от шины APB1. 
//Входную частоту таймера можно поделить с помощью делителя частоты в регистре PSC. А включение таймера производится битом CEN в регистре CR1 модуля TIM5.

Как только таймер начал считать, его счетчик будет увеличиваться с каждым тактом подающейся на таймер частоты. Значение счетчика хранится в регистре CNT, переполнение считывается из регистра SR бита UIF. +
Задать произвольный интервал времени до переполнения можно, используя регистр автоперезагрузки ARR. В этот регистр записывается число, до которого будет идти счет. При достижении этого значения, содержимое счетчика CNT обнуляется и формируются прерывание или запрос DMA.

=== Ход работы

На видео представлена работа программы.

.Видео - Таймер
//video::.mp4[opts="muted"]

== Выводы
[.text-left]
В ходе данной работы было проведено ознакомление с таймерами. Также был написан код, реализующий переключение светодиодов. Результат работы кода был представлен на видео.

[.text-center]
== Ответы на контрольные вопросы
[.text-left]
// закоментировать или убрать, если таковых нет