:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
include::Titul_list_Laba3.adoc[]

toc::[]

---
[.text-left]
== Цель лабораторной работы
Сделать фазовую подстройку частоты (PLL, ФАПЧ). ФАПЧ должен тактироваться на частоте 32 МГц от внутреннего высокочастотного генератора (HSI) 16 МГц.

== Теоретические основы

=== Соглашение об вызовах
Соглашение об вызовах включает в себя:

* Объявление функции
* Компоновка С и С++ кода
* Последовательность использования оперативных регистров и вспомогательные регистровВход в функцию
* Выход из функции
* Обработка адреса возврата

==== Объявление функции
[IMPORTANT]
Функция должна быть объявлена в таком порядке, чтобы компилятор мог узнать как её вызвать.

==== Компоновка С и С++ кода
В C+ +, функция может компоноваться либо как С+ +, либо как С функция. 

Если вы хотите вызвать функции ассемблера из С++, то лучше объявить эту функцию, как имеющую тип компоновки Си

==== Вход в функцию
Параметры передающие в функцию могут использовать два метода:

* Через регистры
* Через стек

Для большей эффективности параметры передаются через регистры, но их число ограничено, поэтому если регистров не хватает, то используется стек. Для передачи параметров используются оперативные регистры *R0:R3*

==== Выход из функции
Функция может вернуть значение. Для возврата значения используются регистры *R0:R1*. Если значение больше 64 бит, то в регистр R0 записывается адрес где лежат данные.

WARNING: Вызывающая функция обязана очистить стек, после того, как вызываемая функция вернула значение.


=== Операторы

Существуют следующие типы операторов:

* Арифметические операторы
* Операторы сравнения
* Логические операторы
* Побитовые операторы
* Составное присваивание
* Операторы работы с указателями и членами класса
* Функторы, тернарные операции, sizeof(), запятая, приведение типа, new

[IMPORTANT]
Все операторы можно переопределить


==== Арифметические операторы
Арифметические операторы предоставляют базовые арифметические действия над типами, такие как сложение, вычитание, деление, умножение, остаток от деления, присваивание.

[#Арифметические операторы]
.Арифметические операторы
[options="header"]
[cols="4,4,4"]
|=====================
|Операция | Оператор | Комментарий
|Присваивание       | =     | a = b
|Сложение           | +     | a + b
|Вычитание          | -     | a - b
|Унарный плюс       | +     | +a
|Унарный минус      | -     | -a
|Умножение          | *     | a * b
|Деление            | /     | a / b
|Остаток от деления | %     | a % b
|Инкремет  (пост и предфиксный)| ++      | &#43;&#43;a  и  a&#43;&#43;
|Декремент (пост и предфиксный)| - -     | --a и a--
|=====================

==== Логические операторы

Логические операторы предоставляют действия над булевым типов. Результат действия этих операторов может быть только *true* или *false*

[#Логические операторы]
.Логические операторы
[options="header"]
[cols="4,4,4,7"]
|=====================
|Операция | Оператор | Комментарий | Пример
|Логическое отрицание, НЕ   | !     | !a    |   !true => false
|Логическое умножение, И    | &&    | a && b| true && false => false
|Логическое сложение, ИЛИ   | &#124;&#124;  |   a &#124; &#124;  b  | true &#124; &#124;  false => true
|=====================

==== Побитовые операторы

Побитовые операторы предоставляют действия с битами.

[#Побитовые операторы]
.Побитовые операторы
[options="header"]
[cols="4,4,4,7"]
|=====================
|Операция | Оператор  | Комментарий | Пример
|Побитовая инверсия   | ~     | ~a  | unsigned char a = 0; ~a => 0xFF
|Побитовое И          | &     | a & b | unsigned char a = 1, b = 3; a & b => 1
|Побитовое ИЛИ        | &#124;   | a &#124; b | unsigned char a = 1, b = 3; a &#124; b => 3
|Побитовое исключающее ИЛИ  | ^   | a ^ b | unsigned char a = 1, b = 3; a ^ b => 2
|Побитовый сдвиг влево  | <<   | a << b | unsigned char a = 1, b = 3; a << b => 8
|Побитовый сдвиг вправо | >>   | a >> b | unsigned char a = 8, b = 3; a >> b => 1
|=====================

=== Ядро CortexM4

* Ядро Cortex построено по гарвардской архитектуре с разделением шины данных и кода. 
* Ядро Cortex-М4 поддерживает 8/16/32-разрядные операции умножения, которые выполняются за 1 цикл (деление со знаком (SDIV) или без (UDIV) занимает от 2 до 12 тактов в зависимости от размера операндов
* Ядро Cortex-М4 поддерживает 8/16/32-разрядные операции умножения со сложением

== Система тактирования

Для формирования системной тактовой частоты SYSCLK могут использоваться 4 основных источника:

* HSI (high-speed internal) — внутренний высокочастотный RC-генератор.
* HSE (high-speed external) — внешний высокочастотный генератор.
* PLL — система ФАПЧ. Точнее сказать, это вовсе и не генератор, а набор из умножителей и делителей, исходный сигнал он получает от HSI или HSE, а на выходе у него уже другая частота. 

Также имеются 2 вторичных источника тактового сигнала:
* LSI (low-speed internal) — низкочастотный внутренний RC-генератор на 37 кГц
* LSE (low-speed external) — низкочастотный внешний источник на 32,768 кГц

=== Фазовая подстройка частоты PLL
PLL Внутренний источник PLL тактируется от внешнего или внутреннего высокочастотных генераторов (HSE либо HSI). 
* С помощью регистров PLLM, PLLN,PLLP можно подобрать любую частоту до 100 Мгц включительно по формуле:
====
   f = f(PLL clock input) × (PLLN / PLLM) /PLLP
====
* Кроме системной тактовой частоты SYSCLK, PLL также выдает частоту 48 МГц для интерфейса USB. При использовании USB входная частота для PLL должна быть в диапазоне от 2 МГц до 24 МГц.
====
   f(USB) = f(PLL clock input) × (PLLN / PLLM) / PLLQ
====

==== Алгоритм настройки частоты
* Определить какие источники частоты нужны
  ** Например, PLL нужен для USB

* Включить нужный источник
** Используя Clock Control register (RCC::CR)

* Дождаться стабилизации источника 
** Используя соответствующие биты (..RDY) Clock Control register (RCC::CR)

* Назначить нужный источник на системную частоту
** Используя Clock Configuration Register (RCC::CFGR)

* Дождаться пока источник не переключиться на системную частоту
** Используя Clock Configuration Register (RCC::CFGR)

== Ход работы

== Выводы
[.text-left]
В ходе данной работы была написана программа, в которой была использована система ФАПЧ для получения частоты тактирования 32 МГц.
Также познакомились с основными операторами языка C++.

[.text-center]
== Ответы на контрольные вопросы
[.text-left]
// закоментировать или убрать, если таковых нет
